# Generated by Django 3.0 on 2022-04-11 08:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import vending_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deposit', models.CharField(default='[0, 0, 0, 0, 0]', max_length=39, validators=[vending_app.models.validate_coin_tab])),
                ('role', models.CharField(choices=[('b', 'Buyer'), ('s', 'Seller')], default='b', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VendingUser',
                'verbose_name_plural': 'VendingUser',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammountAvailable', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField(validators=[vending_app.models.validate_min_nominal])),
                ('productName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vending_app.VendingUser', validators=[vending_app.models.validate_isSeller], verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
